# Generated by Django 5.2.6 on 2025-09-09 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_admin_id_alter_applicant_id_alter_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.applicant'),
        ),
    ]
