# Generated by Django 5.2.6 on 2025-09-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_userprofile_delete_admin_delete_reviewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='fixed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
