# Generated by Django 5.2.6 on 2025-09-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reviewing', 'Reviewing')], default='pending'),
        ),
    ]
