# Generated by Django 5.2.6 on 2025-09-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_fee_alter_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='paid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
